"use client";

import React, { useEffect, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "../ui/card";
import { Input } from "../ui/input";
import { Label } from "../ui/label";
import { CreateBillRequest, CreateBillResponse } from "@/types/bills";
import { Button } from "../ui/button";
import { toast } from "sonner";
import axios from "axios";
import { Popover, PopoverContent, PopoverTrigger } from "../ui/popover";
import { cn } from "@/lib/utils";
import { CalendarIcon } from "lucide-react";
import { format } from "date-fns";
import { Calendar } from "../ui/calendar";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "../ui/dialog";
import { Main } from "../layout/main";
import { IconRefresh } from "@tabler/icons-react";

const Bills = ({ fetchBills }: any) => {
  const [billData, setBillData] = useState<CreateBillRequest>({
    customerName: "",
    email: "",
    phno: "",
    amount: "",
    generatedBy: "",
    serviceTitle: "",
    serviceDesc: "",
    bill_due_date: "",
  });

  const [date, setDate] = React.useState<Date>();

  const handleDateSelect = (day: any) => {
    setDate(day);
    setBillData((prev) => ({
      ...prev,
      bill_due_date: format(day, "yyyy-MM-dd"),
    }));
  };

  useEffect(() => {
    console.log(billData);
  }, [billData]);

  const handleChange = (key: keyof CreateBillRequest) => (event: React.ChangeEvent<HTMLInputElement>) => {
    setBillData((prev) => ({
      ...prev,
      [key]: event.target.value,
    }));
  };

  const handleSubmit = async () => {
    if (
      !billData.customerName ||
      !billData.email ||
      !billData.generatedBy ||
      !billData.serviceTitle ||
      !billData.serviceDesc ||
      !billData.bill_due_date
    ) {
      toast.error("All fields are required");
      return;
    }

    if (parseFloat(billData.amount) <= 0) {
      toast.error("Amount should be greater than zero");
      return;
    }

    if (parseInt(billData.phno) <= 0) {
      toast.error("Phone number should be greater than zero");
      return;
    }

    toast.info("Bill generation in progress");
    try {
      const response = await axios.post("/api/billing", {
        billData,
      });

      if (response.data.error) {
        throw response.data.error;
      }

      fetchBills();
      toast.success(response.data.message);
    } catch (error: string | any) {
      console.log(error);
      toast.error("CODE " + error.status + " " + error.message);
    }
  };

  return (
    <Main>
      <Dialog>
        <DialogTrigger asChild>
          <Button>Create New Bill</Button>
        </DialogTrigger>
        <DialogContent className="sm:max-w-[625px]">
          <DialogHeader>
            <DialogTitle>Create a new bill</DialogTitle>
            <DialogDescription>Create a new bill and hit close when done</DialogDescription>
          </DialogHeader>

          <Card className="mx-auto max-w-[825px]">
            <CardHeader>
              <CardTitle>Bill Generator</CardTitle>
            </CardHeader>
            <CardContent className="space-y-5">
              <div className="flex flex-col md:flex-row gap-5">
                <div className="space-y-5">
                  <div className="flex flex-col gap-3">
                    <Label htmlFor="customerName">Name</Label>
                    <Input id="customerName" placeholder="Name" value={billData.customerName} onChange={handleChange("customerName")} />
                  </div>
                  <div className="flex flex-col gap-3">
                    <Label htmlFor="email">Email</Label>
                    <Input id="email" type="email" placeholder="Email" value={billData.email} onChange={handleChange("email")} />
                  </div>
                  <div className="flex flex-col gap-3">
                    <Label htmlFor="phno">Phone Number</Label>
                    <Input id="phno" type="text" placeholder="Phone Number" value={billData.phno} onChange={handleChange("phno")} />
                  </div>
                  <div className="flex flex-col gap-3">
                    <Label htmlFor="amount">Billing Amount</Label>
                    <Input id="amount" type="text" placeholder="Billing Amount" value={billData.amount} onChange={handleChange("amount")} />
                  </div>
                </div>
                <div className="space-y-5">
                  <div className="flex flex-col gap-3">
                    <Label htmlFor="generatedBy">Generated By</Label>
                    <Input id="generatedBy" placeholder="Generated By" value={billData.generatedBy} onChange={handleChange("generatedBy")} />
                  </div>
                  <div className="flex flex-col gap-3">
                    <Label htmlFor="serviceTitle">Service Title</Label>
                    <Input id="serviceTitle" placeholder="Service Title" value={billData.serviceTitle} onChange={handleChange("serviceTitle")} />
                  </div>
                  <div className="flex flex-col gap-3">
                    <Label htmlFor="serviceDesc">Service Description</Label>
                    <Input id="serviceDesc" placeholder="Service Description" value={billData.serviceDesc} onChange={handleChange("serviceDesc")} />
                  </div>
                  <div className="flex flex-col gap-3">
                    <Label htmlFor="date">Date</Label>
                    <Popover>
                      <PopoverTrigger asChild>
                        <Button variant={"outline"} className={cn("w-[280px] justify-start text-left font-normal", !date && "text-muted-foreground")}>
                          <CalendarIcon className="mr-2 h-4 w-4" />
                          {date ? format(date, "PPP") : <span>Pick a date</span>}
                        </Button>
                      </PopoverTrigger>
                      <PopoverContent className="w-auto p-0">
                        <Calendar mode="single" selected={date} onSelect={handleDateSelect} initialFocus />
                      </PopoverContent>
                    </Popover>
                  </div>
                </div>
              </div>
              <Button onClick={handleSubmit} className="w-full">
                Generate Bill
              </Button>
            </CardContent>
          </Card>
        </DialogContent>
      </Dialog>

      <Button variant={"secondary"} className="ml-3   space-x-1" onClick={() => fetchBills()}>
        Refresh
        <IconRefresh size={18} />
      </Button>
    </Main>
  );
};

export default Bills;
