"use client";
import React, { useMemo, useState } from "react";
import {
  useReactTable,
  getCoreRowModel,
  flexRender,
  SortingState,
  getSortedRowModel,
} from "@tanstack/react-table";
import { Card } from "@/components/ui/card";
import {
  Table,
  TableHead,
  TableHeader,
  TableRow,
  TableCell,
  TableBody,
} from "@/components/ui/table";
import { Skeleton } from "@/components/ui/skeleton";
import { Button } from "@/components/ui/button";
import { ArrowUpDown } from "lucide-react";
import { format } from "date-fns";

const DataTable = ({ data, loading }: any) => {
  const [sorting, setSorting] = React.useState<SortingState>([]);
  const columns = useMemo(
    () => [
      {
        accessorKey: "id",
        header: ({ column }: any) => (
          <Button
            variant="ghost"
            onClick={() => column.toggleSorting(column.getIsSorted() === "asc")}
          >
            ID
            <ArrowUpDown />
          </Button>
        ),
        cell: ({ row }: any) => (
          <div className="ml-5">{row.original["Bill Id"]}</div>
        ),
      },
      {
        accessorKey: "amount",
        header: ({ column }: any) => (
          <Button
            variant="ghost"
            onClick={() => column.toggleSorting(column.getIsSorted() === "asc")}
          >
            Amount
            <ArrowUpDown />
          </Button>
        ),
        cell: ({ row }: any) => (
          <div className="ml-1 pl-5 p-1 pr-5 font-bold text-green-500 bg-green-500/25 rounded-lg">
            {new Intl.NumberFormat("en-IN", {
              style: "currency",
              currency: "INR",
            }).format(row.getValue("amount"))}
          </div>
        ),
      },
      {
        accessorKey: "billDueDate",
        header: ({ column }: any) => (
          <Button
            variant="ghost"
            onClick={() => column.toggleSorting(column.getIsSorted() === "asc")}
          >
            Bill Due Date
            <ArrowUpDown />
          </Button>
        ),
        cell: ({ row }) => (
          <div className="pl-5">
            {format(new Date(row.getValue("billDueDate")), "PP")}
          </div>
        ),
      },
      {
        accessorKey: "billingDate",
        header: ({ column }) => (
          <Button
            variant="ghost"
            onClick={() => column.toggleSorting(column.getIsSorted() === "asc")}
          >
            Billing Date
            <ArrowUpDown />
          </Button>
        ),
        cell: ({ row }) => (
          <div className="pl-5">
            {format(new Date(row.getValue("billingDate")), "PP")}
          </div>
        ),
      },
      {
        accessorKey: "customerName",
        header: ({ column }) => (
          <Button
            variant="ghost"
            onClick={() => column.toggleSorting(column.getIsSorted() === "asc")}
          >
            Customer Name
            <ArrowUpDown />
          </Button>
        ),
        cell: ({ row }) => (
          <div className="pl-5">
            {row
              .getValue("customerName")
              .split(" ")
              .map(
                (word: string) => word.slice(0, 1).toUpperCase() + word.slice(1)
              )
              .join(" ")}
          </div>
        ),
      },
      {
        accessorKey: "email",
        header: ({ column }) => (
          <Button
            variant="ghost"
            onClick={() => column.toggleSorting(column.getIsSorted() === "asc")}
          >
            Email
            <ArrowUpDown />
          </Button>
        ),
        cell: ({ row }) => <div className="pl-5">{row.getValue("email")}</div>,
      },
      {
        accessorKey: "generatedBy",
        header: ({ column }) => (
          <Button
            variant="ghost"
            onClick={() => column.toggleSorting(column.getIsSorted() === "asc")}
          >
            Generated By
            <ArrowUpDown />
          </Button>
        ),
        cell: ({ row }) => (
          <div className="pl-5">{row.getValue("generatedBy")}</div>
        ),
      },
      {
        accessorKey: "status",
        header: ({ column }) => (
          <Button
            variant="ghost"
            onClick={() => column.toggleSorting(column.getIsSorted() === "asc")}
          >
            Status
            <ArrowUpDown />
          </Button>
        ),
        cell: ({ row }) => <div className="pl-5">{row.getValue("status")}</div>,
      },
      {
        accessorKey: "phno",
        header: ({ column }) => (
          <Button
            variant="ghost"
            onClick={() => column.toggleSorting(column.getIsSorted() === "asc")}
          >
            Phone
            <ArrowUpDown />
          </Button>
        ),
        cell: ({ row }) => <div className="pl-5">{row.getValue("phno")}</div>,
      },
      {
        accessorKey: "serviceDesc",
        header: ({ column }) => (
          <Button
            variant="ghost"
            onClick={() => column.toggleSorting(column.getIsSorted() === "asc")}
          >
            Service Description
            <ArrowUpDown />
          </Button>
        ),
        cell: ({ row }) => (
          <div className="pl-5">{row.getValue("serviceDesc")}</div>
        ),
      },
      {
        accessorKey: "serviceTitle",
        header: ({ column }) => (
          <Button
            variant="ghost"
            onClick={() => column.toggleSorting(column.getIsSorted() === "asc")}
          >
            Service Title
            <ArrowUpDown />
          </Button>
        ),
        cell: ({ row }) => (
          <div className="pl-5">{row.getValue("serviceTitle")}</div>
        ),
      },
    ],
    []
  );

  const table = useReactTable({
    data,
    columns,
    onSortingChange: setSorting,
    getCoreRowModel: getCoreRowModel(),
    getSortedRowModel: getSortedRowModel(),
    state: {
      sorting,
    },
  });

  return (
    <Card className="p-4">
      <Table>
        <TableHeader>
          {table.getHeaderGroups().map((headerGroup) => (
            <TableRow key={headerGroup.id}>
              {headerGroup.headers.map((header) => (
                <TableHead key={header.id}>
                  {flexRender(
                    header.column.columnDef.header,
                    header.getContext()
                  )}
                </TableHead>
              ))}
            </TableRow>
          ))}
        </TableHeader>
        <TableBody className="">
          {loading
            ? Array.from({ length: 10 }).map((_, i) => (
                <TableRow key={i}>
                  {Array.from({ length: columns.length }).map((_, j) => (
                    <TableCell key={j}>
                      <Skeleton className="h-8 w-full" />
                    </TableCell>
                  ))}
                </TableRow>
              ))
            : table.getRowModel().rows.map((row) => {
                console.log(row);

                return (
                  <TableRow key={row.id}>
                    {row.getVisibleCells().map((cell) => (
                      <TableCell key={cell.id}>
                        {flexRender(
                          cell.column.columnDef.cell,
                          cell.getContext()
                        )}
                      </TableCell>
                    ))}
                  </TableRow>
                );
              })}
        </TableBody>
      </Table>
    </Card>
  );
};

export default DataTable;
